
---

- hosts: web
  gather_facts: yes
  become: true


  tasks:
    - name: "Add nodejs apt key"
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: "Install nodejs"
      apt:
       update_cache: yes
       name: nodejs
       state: present

    - name: install npm
      apt: pkg=npm state=present

    - name: Install pm2
      npm:
        name: pm2
        global: yes
        production: yes
        state: present

    # Configuration so we can connect to the database
    - name: Exporting the DB_HOST
      become_user: root
      shell: |
        export DB_HOST=mongodb://192.168.10.150:27017/posts >> ~/.bashrc
        cd
        cd app
        pm2 kill
        
  
    - name: Installing node prerequisites and seeding from the database
      shell: |
        cd app
        pm2 start
        node seeds/seed.js

    # - name: Starting the app
    #   shell: |
    #     pm2 kill
    #     pm2 start app.js

    # - name: Stop APP
    #   shell: pm2 kill
    #   args:
    #     chdir: /home/vagrant/app/
    #   ignore_errors: yes

    # - name: Start APP
    #   shell: pm2 start app.js
    #   args:
    #     chdir: /home/vagrant/app/
    #   ignore_errors: yes